version: '3.8'

networks:
  chainlink:
    name: chainlink
    driver: bridge

services:    
   adapter:
      build:
         context: ./
         dockerfile: Dockerfile
      container_name: adapter
      command: sh -c 'npm run build && npm run dev'
      ports:
        - ${PORT}:${PORT}
      networks:
        - chainlink
      tty: true
      restart: always
      volumes:
        - ./:/adapter
        - /adapter/node_modules
  